### ISSUE TITLE
Makerbot package currently uninstalls the software right after install

### ISSUE THREAD

**Issue by groob** [autopkg/groob-recipes#1]
need to make sure Uninstall.pkg is not part of the dmg. Fixing

**Comment by gregneagle** [comment]
Assume you mean when used with Munki; Alternately you could change the Munki pkginfo to explicitly refer to the specific package you want it to install; otherwise it installs _all_ the packages at the root of the DMG, leading to the behavior you note.

See package_path at https://code.google.com/p/munki/wiki/SupportedPkginfoKeys
and the --pkgname option here: https://code.google.com/p/munki/wiki/makepkginfo#Options

**Comment by JCSmillie** [comment]
Ever have any luck working this issue out?  Right now I run the MakerBot.munki recipe and then add to the Package path "MakerBot Bundle BETA 3.4.1.48.pkg"  (current version) to make sure only the installer package is deployed.  An override could probably do this if the version number could be exported to the field?
